[package]
name = "sudachi-vibrato-converter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
once_cell = "1"

[dev-dependencies]
jpreprocess-core = "0.13.2"
tempfile = "3"
vibrato = "0.5.2"
zstd = "0.13"
